import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  topNav: {
    backgroundColor: '#1e3a8a',
    paddingHorizontal: theme.layout.screenPadding,
    paddingBottom: theme.spacing.md,
  },
  headerTopRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.md,
    height: 44,
  },
  searchInput: { flex: 1, fontSize: 14, color: theme.colors.textPrimary },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.error,
    borderWidth: 1,
    borderColor: '#1e3a8a',
  },
  avatarButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  headerAvatar: { width: '100%', height: '100%' },
  content: { flex: 1, zIndex: 5 },
  contentContainer: {
    paddingBottom: theme.spacing.xxxl,
    paddingTop: theme.spacing.lg,
  },

  statsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.md,
    ...theme.shadows.sm,
  },
  statItem: { alignItems: 'center', flex: 1 },
  statDivider: { width: 1, height: 28, backgroundColor: theme.colors.borderLight },
  section: {
    marginBottom: theme.spacing.xl,
    paddingHorizontal: theme.layout.screenPadding,
  },

  liveCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    borderWidth: 1.5,
    borderColor: theme.colors.warning,
    overflow: 'hidden',
    ...theme.shadows.sm,
  },
  liveCardActive: { borderColor: theme.colors.success },
  liveHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.md,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xs,
  },
  liveDotRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    flex: 1,
  },
  liveDotWrapper: {
    width: 10,
    height: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  liveDot: { width: 10, height: 10, borderRadius: 5 },
  liveDotActive: { backgroundColor: theme.colors.success },
  liveDotInactive: { backgroundColor: theme.colors.warning },
  liveDotPing: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.colors.success,
    opacity: 0.3,
  },
  liveLabel: {
    ...theme.typography.body2,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    flexShrink: 1,
  },
  liveBadge: {
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: theme.radius.full,
    marginLeft: theme.spacing.sm,
  },
  liveBadgeActive: { backgroundColor: theme.colors.successBackground },
  liveBadgeInactive: { backgroundColor: theme.colors.warningBackground },
  liveBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  liveBadgeTextActive: { color: '#065f46' },
  liveBadgeTextInactive: { color: '#92400e' },
  liveSubtitle: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    paddingHorizontal: theme.spacing.md,
    paddingBottom: theme.spacing.sm,
  },
  liveDivider: {
    height: 1,
    backgroundColor: theme.colors.borderLight,
    marginHorizontal: theme.spacing.md,
  },
  liveDetailList: {
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    gap: theme.spacing.sm,
  },
  liveDetailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.sm,
  },
  liveDetailText: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    flexShrink: 1,
  },
  liveDetailLabel: {
    fontWeight: '500',
    color: theme.colors.textPrimary,
  },
  liveDetailMarker: {
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveDetailDot: {
    position: 'absolute',
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: theme.colors.textTertiary,
  },
  liveRefreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.sm,
    marginHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.md,
    marginTop: theme.spacing.xs,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.lg,
    borderWidth: 1.5,
    backgroundColor: 'transparent',
  },
  liveRefreshText: {
    ...theme.typography.button,
    fontSize: 13,
  },

  bookingsContainer: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.md,
    ...theme.shadows.sm,
  },
  bookingsSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  seeAllBtn: { flexDirection: 'row', alignItems: 'center' },
  bookingCard: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  bookingHeader: { flexDirection: 'row', alignItems: 'center' },
  bookingInfo: { flex: 1, marginLeft: theme.spacing.sm },
  bookingMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
    marginTop: theme.spacing.md,
    paddingTop: theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: theme.colors.borderLight,
  },

  perfCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.lg,
    ...theme.shadows.sm,
  },
  perfHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.lg,
  },
  perfInfo: { flex: 1, gap: 2 },
  perfStats: { gap: theme.spacing.md },
  perfRow: { gap: theme.spacing.xs },
  perfRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  perfTrack: {
    height: 6,
    backgroundColor: theme.colors.borderLight,
    borderRadius: theme.radius.full,
    overflow: 'hidden',
  },
  perfFill: { height: '100%', borderRadius: theme.radius.full },
});
