packages:
  - apps/*
  - packages/*
  - tests/*

overrides:
  expo-router>@expo/metro-runtime: '6.1.2'

allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  puppeteer: true
  sharp: true
  supabase: true
  unrs-resolver: true
