begin;
create extension if not exists pgtap with schema extensions;
select plan(32);

select has_function('public','cancel_booking',array['uuid','integer','text','text','text','text'],'structured cancellation command exists');
select has_function('public','submit_manual_wallet_topup',array['bigint','text','text','text','text'],'manual top-up command exists');
select has_function('public','admin_review_wallet_topup',array['uuid','text','text'],'manual top-up review exists');
select has_function('public','attach_support_message_media',array['uuid','text','text','integer'],'support attachment command exists');
select has_function('public','register_push_subscription',array['text','text','text'],'push registration command exists');
select has_function('public','remove_push_subscription',array['text'],'push removal command exists');
select has_function('public','admin_duplicate_notification',array['uuid'],'notification duplicate command exists');
select has_function('public','admin_send_notification_now',array['uuid'],'notification send-now command exists');
select has_function('public','admin_archive_notification',array['uuid'],'notification archive command exists');
select has_function('public','get_admin_dashboard_metrics',array['timestamptz','timestamptz'],'admin aggregate command exists');
select has_function('public','submit_worker_onboarding_identity',array['jsonb','text[]'],'structured worker onboarding command exists');
select has_table('public','support_message_attachments','support attachments are persisted');
select has_table('public','push_subscriptions','push subscriptions are persisted');
select has_table('public','push_delivery_attempts','push attempts are persisted');
select has_column('public','report_exports','format','report format is persisted');
select has_column('public','report_exports','filters','report filters are persisted');
select has_column('public','wallet_topups','proof_path','top-up proof is persisted');
select has_column('public','wallet_topups','reviewed_by','top-up review actor is persisted');
select ok((select relrowsecurity from pg_class where oid='public.push_subscriptions'::regclass),'push subscription RLS is enabled');
select ok((select relrowsecurity from pg_class where oid='public.support_message_attachments'::regclass),'support attachment RLS is enabled');
select is(has_function_privilege('anon','public.cancel_booking(uuid,integer,text,text,text,text)','execute'),false,'anonymous cannot cancel bookings');
select is(has_function_privilege('anon','public.submit_manual_wallet_topup(bigint,text,text,text,text)','execute'),false,'anonymous cannot submit top-ups');
select is(has_function_privilege('anon','public.admin_review_wallet_topup(uuid,text,text)','execute'),false,'anonymous cannot review top-ups');
select ok(position('auth.jwt' in pg_get_functiondef('public.admin_review_wallet_topup(uuid,text,text)'::regprocedure)) > 0,'manual top-up decisions require an AAL2 JWT');
select is(has_function_privilege('anon','public.submit_worker_onboarding_identity(jsonb,text[])','execute'),false,'anonymous cannot submit worker identity');
select is(has_column_privilege('authenticated','public.worker_verifications','identity_data','update'),false,'worker identity bypass update is retired');
select ok(position('USE_CANCEL_BOOKING' in pg_get_functiondef('public.transition_booking(uuid,public.booking_status,integer,text)'::regprocedure)) > 0,'generic transition cannot bypass structured cancellation');
select is(to_regprocedure('public.begin_wallet_topup(bigint,text)')::text,null,'legacy provider top-up is retired');
select is(to_regprocedure('public.begin_gcash_payment(uuid,text)')::text,null,'customer GCash entry point is retired');
select is((select public from storage.buckets where id='topup-proofs'),false,'top-up proofs are private');
select is((select public from storage.buckets where id='support-attachments'),false,'support attachments are private');
select is((select count(*) from pgmq.list_queues() where queue_name='push_notifications'),1::bigint,'push queue exists');

select * from finish();
rollback;
