begin;
create extension if not exists pgtap with schema extensions;
select plan(58);
select has_extension('postgis','PostGIS is enabled');
select has_table('public','accounts','accounts exists');
select has_table('public','bookings','bookings exists');
select has_table('public','ai_analysis_attempts','AI provider attempts are auditable');
select has_column('public','worker_profiles','service_origin','worker origin uses geography');
select has_column('public','addresses','location','address uses geography');
select has_column('public','service_requests','service_location','request snapshots geography');
select has_column('public','location_updates','location','tracking uses geography');
select has_table('public','payment_attempts','payment provider attempts are persisted');
select has_table('public','wallet_transactions','worker wallet ledger exists');
select has_table('public','wallet_topups','worker wallet top-ups are persisted');
select has_function('public','submit_manual_wallet_topup',array['bigint','text','text','text','text'],'manual wallet top-up submission is protected');
select has_trigger('public','wallet_topups','protect_successful_wallet_topup','successful wallet top-ups are immutable');
select has_table('public','notification_deliveries','notifications have per-recipient delivery state');
select has_table('public','support_ticket_messages','support replies are persisted');
select has_table('public','worker_verification_documents','verification documents have independent statuses');
select has_table('public','worker_portfolio_items','worker portfolio items are persisted');
select has_table('public','service_request_offers','worker offers are persisted');
select has_table('public','promotions','promotions are persisted');
select has_column('public','bookings','agreed_service_amount','booking price is snapshotted');
select has_function('public','accept_service_offer',array['uuid'],'offer acceptance is atomic');
select has_table('public','admin_session_history','administrator sessions are persisted');
select has_function('public','admin_decide_payout',array['uuid','text','text','text'],'payout decisions are protected');
select has_function('public','record_admin_session',array['text'],'admin login history command exists');
select has_function('public','admin_delete_account',array['uuid','text'],'confirmed User and Worker deletion command exists');
select has_table('public','account_role_memberships','historical role memberships are preserved');
select has_table('public','account_session_roles','obsolete session-role records remain migration-compatible');
select hasnt_function('public','enable_secondary_role',array['account_role'],'secondary role provisioning is removed');
select hasnt_function('public','switch_active_role',array['account_role'],'session role switching is removed');
select hasnt_function('public','get_my_role_context',array[]::text[],'multi-role context is removed');
select has_trigger('public','payments','preserve_successful_payment','successful payments cannot be downgraded');
select has_trigger('public','payment_attempts','preserve_successful_payment_attempt','successful attempts cannot be downgraded');
select has_index('public','worker_profiles','worker_profiles_service_origin_gix','worker geography has GiST index');
select has_index('public','service_requests','service_requests_location_gix','request geography has GiST index');
select has_function('public','transition_booking',array['uuid','booking_status','integer','text'],'booking transition RPC exists');
select has_function('public','confirm_cash_payment',array['uuid','text'],'cash confirmation RPC exists');
select has_function('public','set_worker_service_area',array['numeric','numeric','integer'],'worker service-area RPC exists');
select has_function('public','set_address_location',array['uuid','numeric','numeric'],'address location RPC exists');
select has_function('public','get_booking_tracking',array['uuid','integer'],'authorized tracking RPC exists');
select has_function('public','persist_ai_analysis',array['uuid','text','text','text','text','text','text','text','jsonb','jsonb'],'atomic AI persistence RPC exists');
select has_function('public','admin_create_notification',array['notification_audience','text','text','text','timestamptz'],'protected notification command exists');
select has_function('public','admin_upsert_service_category',array['uuid','text','text','boolean'],'protected category command exists');
select has_function('public','attach_request_media',array['uuid','text','text','integer'],'request media attachment command exists');
select has_function('public','attach_review_media',array['uuid','text','text','integer'],'review media attachment command exists');
select has_function('public','save_ai_analysis',array['uuid'],'AI save command exists');
select ok((select relrowsecurity from pg_class where oid='public.accounts'::regclass),'accounts RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.payments'::regclass),'payments RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.ai_analysis_attempts'::regclass),'AI attempts RLS enabled');
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity),0::bigint,'every public application table enables RLS');
select is((select count(*)::integer from storage.buckets where public=false),10,'all ten application buckets are private');
select is(has_table_privilege('authenticated','public.bookings','insert'),false,'authenticated clients cannot insert bookings directly');
select is((select count(*) from information_schema.routine_privileges where specific_schema='public' and grantee in ('anon','PUBLIC') and privilege_type='EXECUTE' and routine_name in ('transition_booking','confirm_cash_payment','review_worker_verification','read_job_batch')),0::bigint,'anonymous roles cannot execute sensitive RPCs');
select is((select count(*) from information_schema.routine_privileges where specific_schema='public' and grantee in ('anon','PUBLIC') and privilege_type='EXECUTE' and routine_name in ('admin_create_notification','admin_upsert_service_category','attach_request_media','attach_review_media','save_ai_analysis')),0::bigint,'anonymous roles cannot execute UI integration commands');
select is((select count(*) from pg_policies where schemaname='public' and policyname in ('requests_authorized_read','matching_worker_request_media_read')),2::bigint,'non-recursive request and matching-media policies exist');
select is((select count(*) from pg_policies where schemaname='storage' and policyname='storage_matching_worker_request_media_read'),1::bigint,'matching workers can read only attached request-media objects');
select has_trigger('auth','users','provision_account_after_auth_insert','Auth users provision application accounts');
select has_trigger('auth','users','activate_account_after_email_confirmation','email confirmation activates pending accounts');
select throws_ok($$select public.permanently_delete(gen_random_uuid())$$,'42501','PERMANENT_DELETION_BLOCKED','permanent deletion fails closed');
select * from finish();
rollback;
