import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  header: {
    height: 56,
    paddingHorizontal: theme.layout.screenPadding,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  configurationScroll: { flex: 1 },
  configuration: {
    padding: theme.layout.screenPadding,
    gap: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  mapContainer: {
    height: 220,
    borderRadius: theme.radius.xl,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.borderLight,
  },
  configurationMessage: {
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: theme.spacing.lg,
  },
  radiusControlRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: theme.spacing.md,
  },
  controlButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  radiusValue: { flexDirection: 'row', alignItems: 'center' },
  kilometers: {
    color: theme.colors.textSecondary,
    marginLeft: 4,
    marginTop: 8,
  },
  radiusLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.xl,
  },
  rateNotice: {
    padding: theme.spacing.md,
    color: theme.colors.textSecondary,
    backgroundColor: theme.colors.infoBackground,
    borderRadius: theme.radius.lg,
    marginBottom: theme.spacing.md,
  },
  status: {
    marginHorizontal: theme.layout.screenPadding,
    marginBottom: theme.spacing.md,
    padding: theme.spacing.lg,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: theme.spacing.md,
    backgroundColor: theme.colors.infoBackground,
    borderRadius: theme.radius.xl,
  },
  statusCopy: { flex: 1, gap: 4 },
  secondary: { color: theme.colors.textSecondary, textAlign: 'left' },
  matchCount: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  matchCountText: { ...theme.typography.caption, color: theme.colors.primary, fontWeight: '700' },
  timer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: theme.colors.surface,
    padding: 10,
    borderRadius: theme.radius.lg,
  },
  timerText: { ...theme.typography.body2, color: theme.colors.primary, fontWeight: '800' },
  list: { flex: 1 },
  listContent: {
    paddingHorizontal: theme.layout.screenPadding,
    paddingBottom: 32,
    gap: 12,
    flexGrow: 1,
  },
  selectionError: {
    alignItems: 'center',
    backgroundColor: theme.colors.errorBackground,
    borderColor: theme.colors.error,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    padding: theme.spacing.md,
  },
  selectionErrorText: {
    color: theme.colors.error,
    flex: 1,
  },
  empty: {
    flex: 1,
    minHeight: 300,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: theme.spacing.xl,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.colors.infoBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyMessage: {
    ...theme.typography.body2,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.lg,
    gap: 12,
    ...theme.shadows.sm,
  },
  acceptedCard: { borderWidth: 2, borderColor: theme.colors.success },
  workerHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: theme.colors.border,
  },
  statusPill: {
    backgroundColor: theme.colors.info,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
  },
  acceptedPill: { backgroundColor: theme.colors.success },
  pillText: { ...theme.typography.caption, color: '#fff', fontWeight: '700' },
  state: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    paddingHorizontal: theme.layout.screenPadding,
  },
});
