import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.spacing.md,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  content: {
    flex: 1,
    paddingVertical: theme.spacing.lg,
  },
  workerInfo: {
    alignItems: 'center',
    marginBottom: theme.spacing.xl,
  },
  avatarPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: theme.colors.border,
    marginBottom: theme.spacing.md,
  },
  requiredNoticeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.infoBackground,
    borderColor: '#bfdbfe',
    borderWidth: 1,
    padding: theme.spacing.md,
    borderRadius: theme.radius.lg,
    marginBottom: theme.spacing.xl,
    gap: theme.spacing.sm,
  },
  requiredNoticeText: {
    ...theme.typography.body2,
    color: '#1e40af',
    flex: 1,
    fontWeight: '500',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.sm,
    marginTop: theme.spacing.md,
  },
  sectionTitle: {
    marginBottom: 0,
  },
  requiredAsterisk: {
    color: '#ef4444',
    fontWeight: '700',
  },
  requiredBadge: {
    backgroundColor: '#fef2f2',
    borderColor: '#fca5a5',
    borderWidth: 1,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: theme.radius.full,
  },
  requiredBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#dc2626',
    textTransform: 'uppercase',
  },
  optionalBadge: {
    backgroundColor: theme.colors.borderLight,
    borderColor: theme.colors.border,
    borderWidth: 1,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: theme.radius.full,
  },
  optionalBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.textSecondary,
    textTransform: 'uppercase',
  },
  starsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: theme.spacing.md,
  },
  starBtn: {
    padding: theme.spacing.xs,
    marginHorizontal: theme.spacing.xs,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.errorBackground,
    borderColor: '#fca5a5',
    borderWidth: 1,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.md,
    marginBottom: theme.spacing.lg,
    gap: theme.spacing.xs,
  },
  errorText: {
    ...theme.typography.caption,
    color: theme.colors.error,
    fontWeight: '600',
    flex: 1,
  },
  textArea: {
    minHeight: 100,
    backgroundColor: theme.colors.surface,
    marginBottom: theme.spacing.md,
  },
  textAreaError: {
    borderColor: theme.colors.error,
    borderWidth: 1.5,
  },
  photoScroll: {
    flexDirection: 'row',
    marginBottom: theme.spacing.xl,
    flexGrow: 0,
    marginTop: theme.spacing.sm,
  },
  uploadBtn: {
    width: 80,
    height: 80,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.infoBackground,
    marginRight: theme.spacing.md,
  },
  photoPreview: {
    width: 80,
    height: 80,
    borderRadius: theme.radius.md,
    marginRight: theme.spacing.md,
    position: 'relative',
  },
  reviewImage: {
    flex: 1,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.border,
  },
  removePhotoBtn: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  recommendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    marginBottom: theme.spacing.xxxl,
    marginTop: theme.spacing.md,
    ...theme.shadows.sm,
  },
  footer: {
    paddingVertical: theme.spacing.md,
  },
});
