import{prisma}from"../config/database.js";import type{Prisma}from"../generated/prisma/client.js";import{ConflictError,IntegrationError,NotFoundError}from"../utils/errors.js";import{pagination,paginationMeta}from"../utils/pagination.js";import{uploadService}from"./upload.service.js";
const slug=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export class AdminService{
 async dashboard(){const now=new Date(),month=new Date(now.getFullYear(),now.getMonth(),1);const[users,workers,bookings,revenue,pending,recent]=await Promise.all([prisma.user.count({where:{deletedAt:null}}),prisma.workerProfile.count({where:{deletedAt:null}}),prisma.booking.count({where:{deletedAt:null}}),prisma.payment.aggregate({where:{status:"COMPLETED"},_sum:{amount:true}}),prisma.workerProfile.count({where:{verificationStatus:"PENDING",deletedAt:null}}),prisma.auditLog.findMany({include:{actor:{include:{profile:true}}},orderBy:{createdAt:"desc"},take:10})]);const newUsers=await prisma.user.count({where:{createdAt:{gte:month},deletedAt:null}});return{cards:{totalUsers:users,totalWorkers:workers,totalBookings:bookings,totalRevenue:revenue._sum.amount??0,pendingApprovals:pending,newUsers},charts:{bookingTrend:[],revenueTrend:[],categoryDistribution:[]},recentActivity:recent}}
 async users(q:any){const where:Prisma.UserWhereInput={deletedAt:null,roles:{some:{role:{code:"customer"}}},...(q.status?{status:q.status}:{}),...(q.search?{OR:[{email:{contains:q.search,mode:"insensitive"}},{profile:{is:{OR:[{firstName:{contains:q.search,mode:"insensitive"}},{lastName:{contains:q.search,mode:"insensitive"}}]}}}]}:{})};const[items,total]=await prisma.$transaction([prisma.user.findMany({where,...pagination(q.page,q.limit),include:{profile:true,roles:{include:{role:true}},_count:{select:{customerBookings:true}}},orderBy:{createdAt:"desc"}}),prisma.user.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
 async user(id:string){const u=await prisma.user.findFirst({where:{id,deletedAt:null},include:{profile:true,roles:{include:{role:true}},addresses:true,customerBookings:{take:20,orderBy:{createdAt:"desc"}}}});if(!u)throw new NotFoundError("User");return u}
 async status(id:string,status:any){const u=await prisma.user.findFirst({where:{id,deletedAt:null}});if(!u)throw new NotFoundError("User");return prisma.user.update({where:{id},data:{status,tokenVersion:{increment:1},sessions:{updateMany:{where:{revokedAt:null},data:{revokedAt:new Date()}}}}})}
 async workers(q:any){const where:Prisma.WorkerProfileWhereInput={deletedAt:null,...(q.status?{verificationStatus:q.status}:{}),...(q.search?{OR:[{user:{email:{contains:q.search,mode:"insensitive"}}},{user:{profile:{is:{OR:[{firstName:{contains:q.search,mode:"insensitive"}},{lastName:{contains:q.search,mode:"insensitive"}}]}}}},{industry:{name:{contains:q.search,mode:"insensitive"}}}]}:{})};const[items,total]=await prisma.$transaction([prisma.workerProfile.findMany({where,...pagination(q.page,q.limit),include:{user:{include:{profile:true}},industry:true,skills:{include:{skill:true}},documents:{include:{upload:true}}},orderBy:{createdAt:"desc"}}),prisma.workerProfile.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
 async worker(id:string){const w=await prisma.workerProfile.findFirst({where:{OR:[{id},{userId:id}],deletedAt:null},include:{user:{include:{profile:true}},industry:true,skills:{include:{skill:true}},serviceAreas:true,documents:{include:{upload:true}},wallet:true}});if(!w)throw new NotFoundError("Worker");return w}
 async workerDecision(id:string,status:"APPROVED"|"REJECTED"|"NEEDS_DOCUMENTS",remarks?:string){const w=await this.worker(id);const now=new Date();const update:any={verificationStatus:status,rejectionReason:status==="APPROVED"?null:remarks};if(status==="APPROVED")update.approvedAt=now;if(status==="REJECTED")update.rejectedAt=now;return prisma.$transaction(async tx=>{const result=await tx.workerProfile.update({where:{id:w.id},data:update});if(status==="APPROVED")await tx.wallet.upsert({where:{workerId:w.id},create:{workerId:w.id,currency:w.currency},update:{}});return result})}
 async categories(q:any){const where={deletedAt:null,...(q.search?{name:{contains:q.search,mode:"insensitive"as const}}:{})};const[items,total]=await prisma.$transaction([prisma.serviceCategory.findMany({where,...pagination(q.page,q.limit),include:{_count:{select:{services:true}}},orderBy:{name:"asc"}}),prisma.serviceCategory.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
 createCategory(i:any){return prisma.serviceCategory.create({data:{...i,slug:i.slug??slug(i.name)}})}updateCategory(id:string,i:any){return prisma.serviceCategory.update({where:{id},data:{...i,...(i.name&&!i.slug?{slug:slug(i.name)}:{})}})}
 async services(q:any){const where={deletedAt:null,...(q.search?{name:{contains:q.search,mode:"insensitive"as const}}:{})};const[items,total]=await prisma.$transaction([prisma.service.findMany({where,...pagination(q.page,q.limit),include:{category:true},orderBy:{name:"asc"}}),prisma.service.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
 createService(i:any){return prisma.service.create({data:{...i,slug:i.slug??slug(i.name)}})}updateService(id:string,i:any){return prisma.service.update({where:{id},data:{...i,...(i.name&&!i.slug?{slug:slug(i.name)}:{})}})}
 bookings(q:any){return prisma.booking.findMany({where:{deletedAt:null,...(q.status?{status:q.status}:{})},...pagination(q.page,q.limit),include:{customer:{include:{profile:true}},worker:{include:{profile:true}},service:true},orderBy:{createdAt:"desc"}})}
 payments(q:any){return prisma.payment.findMany({where:{...(q.status?{status:q.status}:{})},...pagination(q.page,q.limit),include:{customer:{include:{profile:true}},booking:true,refunds:true},orderBy:{createdAt:"desc"}})}
 async settings(){const v=await prisma.platformSetting.findMany({orderBy:{key:"asc"}});return Object.fromEntries(v.map(x=>[x.key,x.value]))}async updateSettings(uid:string,input:Record<string,unknown>){await prisma.$transaction(Object.entries(input).map(([key,value])=>prisma.platformSetting.upsert({where:{key},create:{key,value:value as any,updatedById:uid},update:{value:value as any,updatedById:uid}})));return this.settings()}
 audit(q:any){return prisma.auditLog.findMany({...pagination(q.page,q.limit),include:{actor:{include:{profile:true}}},orderBy:{createdAt:"desc"}})}trash(q:any){return prisma.deletionRecord.findMany({where:{restoredAt:null,purgedAt:null,...(q.search?{displayName:{contains:q.search,mode:"insensitive"}}:{})},...pagination(q.page,q.limit),orderBy:{deletedAt:"desc"}})}
 async restore(recordId:string){const r=await prisma.deletionRecord.findUnique({where:{id:recordId}});if(!r||r.restoredAt||r.purgedAt)throw new NotFoundError("Deletion record");if(r.entityType!=="User")throw new ConflictError("Restore is not implemented for this entity type","unsupported_restore");await prisma.$transaction([prisma.user.update({where:{id:r.entityId},data:{deletedAt:null,status:"ACTIVE"}}),prisma.deletionRecord.update({where:{id:r.id},data:{restoredAt:new Date()}})]);return{restored:true}}
 async campaigns(q:any){const where={deletedAt:null,...(q.status?{status:q.status}:{})};const[items,total]=await prisma.$transaction([prisma.notificationCampaign.findMany({where,...pagination(q.page,q.limit),include:{_count:{select:{deliveries:true}}},orderBy:{createdAt:"desc"}}),prisma.notificationCampaign.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
 createCampaign(uid:string,input:any){return prisma.notificationCampaign.create({data:{creatorId:uid,...input}})}async campaign(id:string){const c=await prisma.notificationCampaign.findFirst({where:{id,deletedAt:null},include:{deliveries:true}});if(!c)throw new NotFoundError("Campaign");return c}async updateCampaign(id:string,input:any){const c=await this.campaign(id);if(!["DRAFT","SCHEDULED"].includes(c.status))throw new ConflictError("Sent campaigns cannot be edited","invalid_campaign_state");return prisma.notificationCampaign.update({where:{id},data:input})}
 async sendCampaign(id:string){const c=await this.campaign(id);if(!["DRAFT","SCHEDULED"].includes(c.status))throw new ConflictError("Campaign cannot be sent","invalid_campaign_state");if(c.channel!=="IN_APP")throw new IntegrationError(`${c.channel} notification`);const role=c.audience==="WORKERS_ONLY"?"worker":c.audience==="CUSTOMERS_ONLY"?"customer":undefined;const users=await prisma.user.findMany({where:{deletedAt:null,...(c.audience==="INACTIVE_USERS"?{lastLoginAt:{lt:new Date(Date.now()-30*86400000)}}:{status:"ACTIVE"}),...(role?{roles:{some:{role:{code:role}}}}:{})},select:{id:true}});await prisma.$transaction(async tx=>{await tx.notificationCampaign.update({where:{id},data:{status:"SENT",sentAt:new Date()}});if(users.length){await tx.notification.createMany({data:users.map(u=>({recipientId:u.id,type:"campaign",channel:"IN_APP",title:c.title,message:c.message,data:{campaignId:id}}))});await tx.notificationDelivery.createMany({data:users.map(u=>({campaignId:id,recipientId:u.id,status:"DELIVERED",sentAt:new Date()}))})}});return{queued:users.length}}
 async reports(q:any){const[items,total]=await prisma.$transaction([prisma.report.findMany({...pagination(q.page,q.limit),include:{output:{select:{id:true,originalName:true,mimeType:true,sizeBytes:true}}},orderBy:{createdAt:"desc"}}),prisma.report.count()]);return{items:items.map(x=>({...x,downloadUrl:x.outputUploadId?`/api/v1/admin/reports/${x.id}/download`:null})),meta:paginationMeta(q.page,q.limit,total)}}
 async generateReport(uid:string,input:any){const report=await prisma.report.create({data:{requestedById:uid,type:input.type,format:input.format,periodStart:input.from,periodEnd:input.to,status:"PROCESSING"}});try{const[users,workers,bookings,payments]=await Promise.all([prisma.user.count({where:{deletedAt:null}}),prisma.workerProfile.count({where:{deletedAt:null}}),prisma.booking.count({where:{createdAt:{gte:input.from,lte:input.to}}}),prisma.payment.aggregate({where:{status:"COMPLETED",createdAt:{gte:input.from,lte:input.to}},_sum:{amount:true},_count:true})]);const payload={generatedAt:new Date().toISOString(),type:input.type,period:{from:input.from??null,to:input.to??null},summary:{users,workers,bookings,completedPayments:payments._count,revenueMinor:payments._sum.amount??0,currency:"PHP"}};const content=input.format==="csv"?`metric,value\nusers,${users}\nworkers,${workers}\nbookings,${bookings}\ncompletedPayments,${payments._count}\nrevenueMinor,${payments._sum.amount??0}\n`:JSON.stringify(payload,null,2);const buffer=Buffer.from(content);const file={fieldname:"file",originalname:`${input.type}-${report.id}.${input.format}`,encoding:"7bit",mimetype:input.format==="csv"?"text/csv":"application/json",size:buffer.length,buffer,stream:null as any,destination:"",filename:"",path:""};const upload=await uploadService.create(uid,"report",file,"PRIVATE");return prisma.report.update({where:{id:report.id},data:{status:"COMPLETED",completedAt:new Date(),outputUploadId:upload.id},include:{output:true}})}catch(error){await prisma.report.update({where:{id:report.id},data:{status:"FAILED",errorMessage:error instanceof Error?error.message.slice(0,1000):"Report failed"}});throw error}}
 async reportDownload(uid:string,roles:string[],id:string){const r=await prisma.report.findUnique({where:{id}});if(!r?.outputUploadId)throw new ConflictError("Report is not ready","report_not_ready");return uploadService.get(uid,roles,r.outputUploadId)}
}
export const adminService=new AdminService();
