import { randomBytes } from "node:crypto";
import { prisma } from "../config/database.js";
import type { Prisma } from "../generated/prisma/client.js";
import { AuthorizationError, ConflictError, IntegrationError, NotFoundError } from "../utils/errors.js";
import { pagination,paginationMeta } from "../utils/pagination.js";
import { env } from "../config/env.js";

const admin=(r:string[])=>r.includes("admin")||r.includes("super_admin");
export class DomainService {
 async conversations(uid:string,q:any){const where={participants:{some:{userId:uid}}};const [items,total]=await prisma.$transaction([prisma.conversation.findMany({where,...pagination(q.page,q.limit),include:{participants:{include:{user:{include:{profile:true}}}},messages:{where:{deletedAt:null},orderBy:{createdAt:"desc"},take:1}},orderBy:{updatedAt:"desc"}}),prisma.conversation.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
 async createConversation(uid:string,input:any){const ids=[...new Set([uid,...input.participantIds])];if(input.bookingId){const b=await prisma.booking.findFirst({where:{id:input.bookingId,OR:[{customerId:uid},{workerId:uid}]}});if(!b)throw new AuthorizationError()}const users=await prisma.user.count({where:{id:{in:ids},deletedAt:null}});if(users!==ids.length)throw new NotFoundError("Participant");return prisma.conversation.create({data:{requestId:input.requestId,bookingId:input.bookingId,participants:{createMany:{data:ids.map(userId=>({userId}))}}},include:{participants:true}})}
 async assertParticipant(uid:string,id:string){const c=await prisma.conversation.findFirst({where:{id,participants:{some:{userId:uid}}}});if(!c)throw new NotFoundError("Conversation");return c}
 async messages(uid:string,id:string,q:any){await this.assertParticipant(uid,id);const items=await prisma.message.findMany({where:{conversationId:id,deletedAt:null,...(q.cursor?{createdAt:{lt:new Date(q.cursor)}}:{})},include:{sender:{include:{profile:true}},attachments:{include:{upload:true}}},orderBy:{createdAt:"desc"},take:Math.min(Number(q.limit)||30,100)});return{items,nextCursor:items.at(-1)?.createdAt??null}}
 async send(uid:string,id:string,input:any){await this.assertParticipant(uid,id);if(input.attachmentIds.length){const n=await prisma.upload.count({where:{id:{in:input.attachmentIds},ownerId:uid,status:"ACTIVE",deletedAt:null}});if(n!==new Set(input.attachmentIds).size)throw new NotFoundError("Attachment")};return prisma.$transaction(async tx=>{const m=await tx.message.create({data:{conversationId:id,senderId:uid,text:input.text}});if(input.attachmentIds.length){await tx.messageAttachment.createMany({data:input.attachmentIds.map((uploadId:string)=>({messageId:m.id,uploadId}))});await tx.upload.updateMany({where:{id:{in:input.attachmentIds}},data:{attachedAt:new Date()}})}await tx.conversation.update({where:{id},data:{updatedAt:new Date()}});return tx.message.findUnique({where:{id:m.id},include:{attachments:{include:{upload:true}}}})})}
 async read(uid:string,id:string){await this.assertParticipant(uid,id);return prisma.conversationParticipant.update({where:{conversationId_userId:{conversationId:id,userId:uid}},data:{lastReadAt:new Date()}})}
 async deleteMessage(uid:string,roles:string[],id:string){const m=await prisma.message.findUnique({where:{id}});if(!m)throw new NotFoundError("Message");if(m.senderId!==uid&&!admin(roles))throw new AuthorizationError();await prisma.message.update({where:{id},data:{deletedAt:new Date(),text:null}})}

 async reviews(q:any){const where:Prisma.ReviewWhereInput={deletedAt:null,status:q.status??"PUBLISHED",...(q.providerId?{subjectId:q.providerId}:{}),...(q.rating?{rating:q.rating}:{}),...(q.search?{comment:{contains:q.search,mode:"insensitive"}}:{})};const [items,total]=await prisma.$transaction([prisma.review.findMany({where,...pagination(q.page,q.limit),include:{author:{include:{profile:true}},subject:{include:{profile:true}},replies:true},orderBy:{createdAt:"desc"}}),prisma.review.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
 async createReview(uid:string,input:any){const b=await prisma.booking.findFirst({where:{id:input.bookingId,status:"COMPLETED",OR:[{customerId:uid},{workerId:uid}]}});if(!b)throw new ConflictError("Only participants can review a completed booking","invalid_review_state");if(input.photoUploadIds.length){const n=await prisma.upload.count({where:{id:{in:input.photoUploadIds},ownerId:uid,purpose:"review",status:"ACTIVE",deletedAt:null}});if(n!==new Set(input.photoUploadIds).size)throw new NotFoundError("Review photo")};const subjectId=b.customerId===uid?b.workerId:b.customerId;try{const review=await prisma.$transaction(async tx=>{const row=await tx.review.create({data:{bookingId:b.id,authorId:uid,subjectId,rating:input.rating,comment:input.comment,recommend:input.recommend}});if(input.photoUploadIds.length){await tx.reviewAttachment.createMany({data:input.photoUploadIds.map((uploadId:string)=>({reviewId:row.id,uploadId}))});await tx.upload.updateMany({where:{id:{in:input.photoUploadIds}},data:{attachedAt:new Date()}})}return row});await this.recalculateRating(subjectId);return review}catch(error){if(error instanceof NotFoundError)throw error;throw new ConflictError("This booking has already been reviewed","duplicate_review")}}
 async review(id:string){const r=await prisma.review.findFirst({where:{id,deletedAt:null,status:"PUBLISHED"},include:{author:{include:{profile:true}},subject:{include:{profile:true}},replies:true}});if(!r)throw new NotFoundError("Review");return r}
 async updateReview(uid:string,id:string,input:any){const r=await prisma.review.findFirst({where:{id,authorId:uid,deletedAt:null}});if(!r)throw new NotFoundError("Review");const updated=await prisma.review.update({where:{id},data:{rating:input.rating,comment:input.comment,recommend:input.recommend}});await this.recalculateRating(r.subjectId);return updated}
 async deleteReview(uid:string,roles:string[],id:string){const r=await prisma.review.findUnique({where:{id}});if(!r)throw new NotFoundError("Review");if(r.authorId!==uid&&!admin(roles))throw new AuthorizationError();await prisma.review.update({where:{id},data:{deletedAt:new Date()}});await this.recalculateRating(r.subjectId)}
 async vote(uid:string,id:string,helpful:boolean){await this.review(id);await prisma.reviewVote.upsert({where:{reviewId_userId:{reviewId:id,userId:uid}},create:{reviewId:id,userId:uid,helpful},update:{helpful}});const count=await prisma.reviewVote.count({where:{reviewId:id,helpful:true}});return prisma.review.update({where:{id},data:{helpfulCount:count}})}
 async report(uid:string,id:string,input:any){await this.review(id);try{return await prisma.$transaction(async tx=>{const report=await tx.reviewReport.create({data:{reviewId:id,userId:uid,...input}});await tx.review.update({where:{id},data:{reportCount:{increment:1}}});return report})}catch{throw new ConflictError("Review already reported","duplicate_report")}}
 async reviewReply(uid:string,id:string,message:string){await this.review(id);return prisma.reviewReply.create({data:{reviewId:id,authorId:uid,message}})}
 async moderateReview(id:string,input:any){const r=await prisma.review.findFirst({where:{id,deletedAt:null}});if(!r)throw new NotFoundError("Review");const updated=await prisma.review.update({where:{id},data:{status:input.status}});await this.recalculateRating(r.subjectId);return updated}
 async recalculateRating(subjectId:string){const a=await prisma.review.aggregate({where:{subjectId,status:"PUBLISHED",deletedAt:null},_avg:{rating:true},_count:true});await prisma.workerProfile.updateMany({where:{userId:subjectId},data:{ratingAverage:a._avg.rating??0,ratingCount:a._count}})}

 async notifications(uid:string,q:any){const where={recipientId:uid,deletedAt:null,...(q.unread?{readAt:null}:{}),...(q.type?{type:q.type}:{})};const [items,total,unread]=await prisma.$transaction([prisma.notification.findMany({where,...pagination(q.page,q.limit),orderBy:{createdAt:"desc"}}),prisma.notification.count({where}),prisma.notification.count({where:{recipientId:uid,readAt:null,deletedAt:null}})]);return{items,unread,meta:paginationMeta(q.page,q.limit,total)}}
 async notificationRead(uid:string,id:string){const n=await prisma.notification.updateMany({where:{id,recipientId:uid,deletedAt:null},data:{readAt:new Date()}});if(!n.count)throw new NotFoundError("Notification");return prisma.notification.findUnique({where:{id}})}
 async notificationReadAll(uid:string){const r=await prisma.notification.updateMany({where:{recipientId:uid,readAt:null,deletedAt:null},data:{readAt:new Date()}});return{updated:r.count}}
 async notificationDelete(uid:string,id:string){const r=await prisma.notification.updateMany({where:{id,recipientId:uid,deletedAt:null},data:{deletedAt:new Date()}});if(!r.count)throw new NotFoundError("Notification")}

 async tickets(uid:string,roles:string[],q:any){const where:Prisma.SupportTicketWhereInput={deletedAt:null,...(admin(roles)?{}:{reporterId:uid}),...(q.status?{status:q.status}:{}),...(q.search?{OR:[{subject:{contains:q.search,mode:"insensitive"}},{reference:{contains:q.search,mode:"insensitive"}}]}:{})};const [items,total]=await prisma.$transaction([prisma.supportTicket.findMany({where,...pagination(q.page,q.limit),include:{reporter:{include:{profile:true}},assignee:{include:{profile:true}}},orderBy:{createdAt:"desc"}}),prisma.supportTicket.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
 async createTicket(uid:string,input:any){if(input.attachmentIds.length){const n=await prisma.upload.count({where:{id:{in:input.attachmentIds},ownerId:uid,purpose:"support",status:"ACTIVE",deletedAt:null}});if(n!==new Set(input.attachmentIds).size)throw new NotFoundError("Support attachment")};const reference=`TKT-${Date.now().toString(36).toUpperCase()}-${randomBytes(2).toString("hex").toUpperCase()}`;return prisma.$transaction(async tx=>{const ticket=await tx.supportTicket.create({data:{reference,reporterId:uid,subject:input.subject,category:input.category,priority:input.priority,bookingId:input.bookingId}});const message=await tx.supportMessage.create({data:{ticketId:ticket.id,authorId:uid,message:input.message}});if(input.attachmentIds.length){await tx.supportMessageAttachment.createMany({data:input.attachmentIds.map((uploadId:string)=>({messageId:message.id,uploadId}))});await tx.upload.updateMany({where:{id:{in:input.attachmentIds}},data:{attachedAt:new Date()}})}return tx.supportTicket.findUnique({where:{id:ticket.id},include:{messages:{include:{attachments:true}}}})})}
 async ticket(uid:string,roles:string[],id:string){const t=await prisma.supportTicket.findFirst({where:{id,deletedAt:null},include:{reporter:{include:{profile:true}},assignee:{include:{profile:true}},messages:{where:admin(roles)?{}:{internal:false},include:{author:{include:{profile:true}},attachments:{include:{upload:true}}},orderBy:{createdAt:"asc"}}}});if(!t)throw new NotFoundError("Ticket");if(t.reporterId!==uid&&!admin(roles))throw new AuthorizationError();return t}
 async ticketMessage(uid:string,roles:string[],id:string,input:any){const t=await this.ticket(uid,roles,id);if(input.attachmentIds.length){const n=await prisma.upload.count({where:{id:{in:input.attachmentIds},ownerId:uid,purpose:"support",status:"ACTIVE",deletedAt:null}});if(n!==new Set(input.attachmentIds).size)throw new NotFoundError("Support attachment")};return prisma.$transaction(async tx=>{const message=await tx.supportMessage.create({data:{ticketId:id,authorId:uid,message:input.message,internal:false}});if(input.attachmentIds.length){await tx.supportMessageAttachment.createMany({data:input.attachmentIds.map((uploadId:string)=>({messageId:message.id,uploadId}))});await tx.upload.updateMany({where:{id:{in:input.attachmentIds}},data:{attachedAt:new Date()}})}if(t.status==="RESOLVED"||t.status==="CLOSED")await tx.supportTicket.update({where:{id},data:{status:"OPEN",resolvedAt:null}});return message})}
 async updateTicket(id:string,input:any){const t=await prisma.supportTicket.findFirst({where:{id,deletedAt:null}});if(!t)throw new NotFoundError("Ticket");return prisma.supportTicket.update({where:{id},data:input})}
 async resolveTicket(id:string,resolution?:string){return this.updateTicket(id,{status:"RESOLVED",resolution,resolvedAt:new Date()})}
 async reopenTicket(uid:string,roles:string[],id:string){await this.ticket(uid,roles,id);return prisma.supportTicket.update({where:{id},data:{status:"OPEN",resolvedAt:null,resolution:null}})}

 async payment(uid:string,input:any){const booking=await prisma.booking.findFirst({where:{id:input.bookingId,customerId:uid,deletedAt:null}});if(!booking)throw new NotFoundError("Booking");const existing=await prisma.payment.findUnique({where:{idempotencyKey:input.idempotencyKey}});if(existing)return existing;return prisma.payment.create({data:{bookingId:booking.id,customerId:uid,provider:env.NODE_ENV==="production"?"unconfigured":"development",idempotencyKey:input.idempotencyKey,method:input.method,amount:booking.amount+booking.platformFee,currency:booking.currency,reference:`PAY-${randomBytes(8).toString("hex").toUpperCase()}`}})}
 async confirmPayment(uid:string,id:string){const p=await prisma.payment.findFirst({where:{id,customerId:uid},include:{booking:{include:{worker:{include:{workerProfile:true}}}}}});if(!p)throw new NotFoundError("Payment");if(env.NODE_ENV==="production")throw new IntegrationError("Payment provider");if(p.status==="COMPLETED")return p;return prisma.$transaction(async tx=>{const done=await tx.payment.update({where:{id},data:{status:"COMPLETED",completedAt:new Date()}});const wp=p.booking.worker.workerProfile;if(wp){const wallet=await tx.wallet.upsert({where:{workerId:wp.id},create:{workerId:wp.id,currency:p.currency},update:{}});await tx.wallet.update({where:{id:wallet.id},data:{balance:{increment:p.amount},version:{increment:1}}});await tx.walletTransaction.create({data:{walletId:wallet.id,paymentId:p.id,type:"JOB_EARNING",direction:"CREDIT",amount:p.amount,currency:p.currency,status:"COMPLETED",description:`Booking ${p.bookingId} payment`,completedAt:new Date()}})}return done})}
 async paymentDetail(uid:string,roles:string[],id:string){const p=await prisma.payment.findUnique({where:{id},include:{booking:true,refunds:true,events:true}});if(!p)throw new NotFoundError("Payment");if(!admin(roles)&&p.customerId!==uid&&p.booking.workerId!==uid)throw new AuthorizationError();return p}
 async refund(uid:string,roles:string[],id:string,input:any){const p=await this.paymentDetail(uid,roles,id);if(p.status!=="COMPLETED"&&p.status!=="PARTIALLY_REFUNDED")throw new ConflictError("Only completed payments can be refunded","invalid_payment_state");const refunded=p.refunds.filter(x=>x.status==="COMPLETED").reduce((n,x)=>n+x.amount,0);const amount=input.amount??p.amount-refunded;if(amount<=0||amount>p.amount-refunded)throw new ConflictError("Refund amount exceeds the remaining paid amount","invalid_refund_amount");return prisma.$transaction(async tx=>{const refund=await tx.refund.create({data:{paymentId:id,requestedById:uid,amount,currency:p.currency,reason:input.reason,status:env.NODE_ENV==="production"?"PENDING":"COMPLETED",...(env.NODE_ENV!=="production"?{completedAt:new Date()}:{})}});if(env.NODE_ENV!=="production")await tx.payment.update({where:{id},data:{status:amount===p.amount-refunded?"REFUNDED":"PARTIALLY_REFUNDED"}});return refund})}
 async transactions(uid:string,roles:string[],q:any){if(roles.includes("worker")){const wp=await prisma.workerProfile.findUnique({where:{userId:uid},include:{wallet:true}});if(!wp?.wallet)return{items:[],meta:paginationMeta(q.page,q.limit,0)};const where={walletId:wp.wallet.id};const [items,total]=await prisma.$transaction([prisma.walletTransaction.findMany({where,...pagination(q.page,q.limit),orderBy:{createdAt:"desc"}}),prisma.walletTransaction.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}const where={customerId:uid};const [items,total]=await prisma.$transaction([prisma.payment.findMany({where,...pagination(q.page,q.limit),orderBy:{createdAt:"desc"}}),prisma.payment.count({where})]);return{items,meta:paginationMeta(q.page,q.limit,total)}}
}
export const domainService=new DomainService();
