import { corsHeaders,corsHeadersFor,failure,handleError,HttpError,jsonBody,success } from "../_shared/http.ts";
import { requestContext } from "../_shared/supabase.ts";
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const pageOf=(url:URL)=>{const page=Math.max(1,Number(url.searchParams.get('page')??1));const limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit')??20)));return{page,limit,from:(page-1)*limit,to:page*limit-1}};
Deno.serve(async(request)=>{Object.assign(corsHeaders,corsHeadersFor(request));if(request.method==='OPTIONS')return new Response('ok',{headers:corsHeadersFor(request)});try{const{client,admin,user}=await requestContext(request);const url=new URL(request.url);const marker=url.pathname.indexOf('/api');const path=(marker>=0?url.pathname.slice(marker+4):url.pathname).replace(/\/+$/,'')||'/';const segments=path.split('/').filter(Boolean);const paging=pageOf(url);
if(request.method==='GET'&&path==='/health')return success({status:'ready',project:'qsurouiyvisykjkgjqmz'});
if(request.method==='GET'&&path==='/me'){const[{data:account,error},{data:roles}]=await Promise.all([client.from('accounts').select('id,email,mobile,role,status,deleted_at,user_profiles(*),worker_profiles(*),admin_profiles(*)').eq('id',user.id).single(),client.rpc('get_my_role_context')]);if(error)throw error;return success({...account,roleContext:roles});}
if(request.method==='GET'&&path==='/categories'){const{data,error,count}=await client.from('service_categories').select('*,services(count)',{count:'exact'}).eq('is_active',true).order('name').range(paging.from,paging.to);if(error)throw error;return success({items:data,meta:{...paging,total:count??0,totalPages:Math.ceil((count??0)/paging.limit)}});}
if(request.method==='GET'&&path==='/services'){let query=client.from('services').select('*,service_categories(*)',{count:'exact'}).eq('is_active',true);const search=url.searchParams.get('search');const category=url.searchParams.get('categoryId');if(search)query=query.ilike('name',`%${search.replaceAll('%','')}%`);if(category)query=query.eq('category_id',category);const{data,error,count}=await query.order('name').range(paging.from,paging.to);if(error)throw error;return success({items:data,meta:{...paging,total:count??0,totalPages:Math.ceil((count??0)/paging.limit)}});}
if(request.method==='GET'&&path==='/providers'){let query=client.from('worker_profiles').select('*,worker_skills(*,service_categories(*)),worker_offerings(*,services(*))',{count:'exact'}).eq('approval_status','APPROVED').eq('is_available',true);const{data,error,count}=await query.range(paging.from,paging.to);if(error)throw error;return success({items:data,meta:{...paging,total:count??0,totalPages:Math.ceil((count??0)/paging.limit)}});}
if(request.method==='GET'&&path==='/requests'){const{data,error,count}=await client.from('service_requests').select('*,service_categories(*),addresses(*),request_bids(*)',{count:'exact'}).order('created_at',{ascending:false}).range(paging.from,paging.to);if(error)throw error;return success({items:data,meta:{...paging,total:count??0,totalPages:Math.ceil((count??0)/paging.limit)}});}
if(request.method==='POST'&&path==='/requests'){const body=await jsonBody(request);const{data,error}=await client.rpc('create_service_request',{category_id:body.categoryId,address_id:body.addressId,description:body.description,scheduled_at:body.scheduledAt,budget:body.budget,notes:body.notes??null,ai_analysis_id:body.aiAnalysisId??null,notify_on_match:Boolean(body.notifyOnMatch)});if(error)throw error;return success(data,'Request created',201);}
if(request.method==='GET'&&path==='/bookings'){const{data,error,count}=await client.from('bookings').select('*,service_requests(*,service_categories(*),addresses(*)),payments(*),booking_status_events(*)',{count:'exact'}).order('created_at',{ascending:false}).range(paging.from,paging.to);if(error)throw error;return success({items:data,meta:{...paging,total:count??0,totalPages:Math.ceil((count??0)/paging.limit)}});}
if(request.method==='POST'&&segments[0]==='bookings'&&uuid.test(segments[1]??'')&&segments[2]==='transitions'){const body=await jsonBody(request);const{data,error}=await client.rpc('transition_booking',{target_booking:segments[1],action:body.action,expected_version:body.version??null});if(error)throw error;return success(data,'Booking updated');}
if(request.method==='GET'&&path==='/conversations'){const{data,error}=await client.from('conversation_participants').select('conversation_id,joined_at,conversations(*,messages(*,message_attachments(*)))').eq('account_id',user.id).range(paging.from,paging.to);if(error)throw error;return success({items:data,meta:{...paging,total:data?.length??0,totalPages:(data?.length??0)?1:0}});}
if(request.method==='POST'&&segments[0]==='conversations'&&uuid.test(segments[1]??'')&&segments[2]==='messages'){const body=await jsonBody(request);const text=typeof body.text==='string'?body.text.trim():'';if(!text)throw new HttpError(422,'message_required','Message text is required');const{data,error}=await client.from('messages').insert({conversation_id:segments[1],sender_id:user.id,body:text,original_locale:body.locale??null}).select().single();if(error)throw error;return success(data,'Message sent',201);}
if(request.method==='GET'&&path==='/notifications'){const{data,error,count}=await client.from('notifications').select('*',{count:'exact'}).eq('recipient_id',user.id).order('created_at',{ascending:false}).range(paging.from,paging.to);if(error)throw error;return success({items:data,meta:{...paging,total:count??0,totalPages:Math.ceil((count??0)/paging.limit)}});}
if(request.method==='PATCH'&&segments[0]==='notifications'&&uuid.test(segments[1]??'')&&segments[2]==='read'){const{data,error}=await client.rpc('mark_notification_read',{p_notification_id:segments[1]});if(error)throw error;return success(data,'Notification read');}
if(path.startsWith('/admin/')){const{data:isAdmin}=await client.rpc('is_admin',{require_aal2:false});if(!isAdmin)throw new HttpError(403,'forbidden','Administrator access required');if(request.method==='GET'&&path==='/admin/dashboard'){const{data,error}=await client.rpc('admin_dashboard_metrics');if(error)throw error;return success(data);}const tableByPath:{[key:string]:string}={users:'accounts',workers:'worker_profiles',bookings:'bookings',payments:'payments',reviews:'reviews',support:'support_tickets',audit:'audit_logs',settings:'system_settings',reports:'report_exports','ai-jobs':'ai_analysis_jobs'};const table=tableByPath[segments[1]];if(request.method==='GET'&&table){const{data,error,count}=await admin.from(table).select('*',{count:'exact'}).order(table==='system_settings'?'key':'created_at',{ascending:table==='system_settings'}).range(paging.from,paging.to);if(error)throw error;return success({items:data,meta:{...paging,total:count??0,totalPages:Math.ceil((count??0)/paging.limit)}});}}
return failure(404,'not_found','Endpoint not found');}catch(error){return handleError(error);}});
