import type { Request, Response } from "express";
import { createReadStream } from "node:fs";
import { adminService as a } from "../services/admin.service.js";
import { writeAudit } from "../services/audit.service.js";
import { sendSuccess } from "../utils/response.js";
const ok=(s:Response,x:unknown,m?:string,c?:number)=>sendSuccess(s,x,m,c);
export const adminController={
 dashboard:async(_:Request,s:Response)=>ok(s,await a.dashboard()),users:async(r:Request,s:Response)=>ok(s,await a.users(r.query)),user:async(r:Request,s:Response)=>ok(s,await a.user(String(r.params.id))),
 userStatus:async(r:Request,s:Response)=>{const x=await a.status(String(r.params.id),r.body.status);await writeAudit(r,{action:"user.status",module:"users",targetType:"User",targetId:x.id,metadata:{status:r.body.status,reason:r.body.reason}});return ok(s,x,"Status updated")},
 workers:async(r:Request,s:Response)=>ok(s,await a.workers(r.query)),worker:async(r:Request,s:Response)=>ok(s,await a.worker(String(r.params.id))),
 approve:async(r:Request,s:Response)=>{const x=await a.workerDecision(String(r.params.id),"APPROVED",r.body.remarks);await writeAudit(r,{action:"worker.approve",module:"workers",targetId:x.id});return ok(s,x,"Worker approved")},
 reject:async(r:Request,s:Response)=>ok(s,await a.workerDecision(String(r.params.id),"REJECTED",r.body.remarks),"Worker rejected"),documents:async(r:Request,s:Response)=>ok(s,await a.workerDecision(String(r.params.id),"NEEDS_DOCUMENTS",r.body.remarks),"Documents requested"),
 categories:async(r:Request,s:Response)=>ok(s,await a.categories(r.query)),createCategory:async(r:Request,s:Response)=>ok(s,await a.createCategory(r.body),"Category created",201),updateCategory:async(r:Request,s:Response)=>ok(s,await a.updateCategory(String(r.params.id),r.body),"Category updated"),
 services:async(r:Request,s:Response)=>ok(s,await a.services(r.query)),createService:async(r:Request,s:Response)=>ok(s,await a.createService(r.body),"Service created",201),updateService:async(r:Request,s:Response)=>ok(s,await a.updateService(String(r.params.id),r.body),"Service updated"),
 bookings:async(r:Request,s:Response)=>ok(s,await a.bookings(r.query)),payments:async(r:Request,s:Response)=>ok(s,await a.payments(r.query)),settings:async(_:Request,s:Response)=>ok(s,await a.settings()),updateSettings:async(r:Request,s:Response)=>ok(s,await a.updateSettings(r.auth!.userId,r.body),"Settings updated"),audit:async(r:Request,s:Response)=>ok(s,await a.audit(r.query)),trash:async(r:Request,s:Response)=>ok(s,await a.trash(r.query)),restore:async(r:Request,s:Response)=>ok(s,await a.restore(String(r.params.id)),"Record restored"),
 campaigns:async(r:Request,s:Response)=>ok(s,await a.campaigns(r.query)),createCampaign:async(r:Request,s:Response)=>ok(s,await a.createCampaign(r.auth!.userId,r.body),"Campaign created",201),campaign:async(r:Request,s:Response)=>ok(s,await a.campaign(String(r.params.id))),updateCampaign:async(r:Request,s:Response)=>ok(s,await a.updateCampaign(String(r.params.id),r.body),"Campaign updated"),sendCampaign:async(r:Request,s:Response)=>ok(s,await a.sendCampaign(String(r.params.id)),"Campaign sent",202),
 reports:async(r:Request,s:Response)=>ok(s,await a.reports(r.query)),generateReport:async(r:Request,s:Response)=>ok(s,await a.generateReport(r.auth!.userId,r.body),"Report generated",201),reportDownload:async(r:Request,s:Response)=>{const{upload,path}=await a.reportDownload(r.auth!.userId,r.auth!.roles,String(r.params.id));s.type(upload.mimeType).set("Content-Disposition",`attachment; filename*=UTF-8''${encodeURIComponent(upload.originalName)}`);createReadStream(path).pipe(s)}
};
