import { theme } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.spacing.md,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  content: {
    flex: 1,
    paddingHorizontal: theme.layout.screenPadding,
    paddingVertical: theme.spacing.xl,
  },
  title: { marginBottom: theme.spacing.xl, color: theme.colors.textPrimary },
  sectionTitle: {
    marginBottom: theme.spacing.sm,
    color: theme.colors.textPrimary,
  },
  serviceSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.sm,
  },
  serviceSearchToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.infoBackground,
  },
  serviceSearchToggleText: {
    ...theme.typography.caption,
    color: theme.colors.primary,
    fontWeight: '700',
  },
  serviceSearchInput: { minHeight: 44 },

  categoriesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.sm,
  },
  categoriesRowComplete: { marginBottom: theme.spacing.xl },
  categoryItemRow: {
    width: '23%',
    height: 80,
    marginBottom: theme.spacing.md,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  categoryItemSelected: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.infoBackground,
  },
  seeMoreServicesButton: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
    marginBottom: theme.spacing.xl,
  },
  seeMoreServicesText: {
    ...theme.typography.button,
    color: theme.colors.primary,
    fontSize: 13,
  },
  noServicesState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: theme.spacing.xl,
  },
  noServicesText: {
    ...theme.typography.body2,
    color: theme.colors.textSecondary,
    marginTop: theme.spacing.sm,
  },
  fieldError: {
    ...theme.typography.caption,
    color: theme.colors.error,
    marginTop: theme.spacing.xs,
    marginBottom: theme.spacing.sm,
  },

  mediaUploadBtn: {
    width: '100%',
    height: 80,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.infoBackground,
    marginBottom: theme.spacing.sm,
  },
  photoActionRow: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
  },
  photoAction: {
    flex: 1,
    width: undefined,
  },
  mediaPreview: {
    width: '100%',
    height: 120,
    borderRadius: theme.radius.md,
    position: 'relative',
    overflow: 'hidden',
    marginBottom: theme.spacing.sm,
  },
  mediaImg: {
    width: '100%',
    height: '100%',
    backgroundColor: theme.colors.border,
  },
  voiceLabelOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 8,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  removeMediaBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.colors.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mediaStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
    padding: theme.spacing.sm,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.infoBackground,
  },
  mediaStatusText: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    flex: 1,
  },
  mediaRetryText: {
    ...theme.typography.caption,
    color: theme.colors.primary,
    fontWeight: '700',
  },

  textArea: {
    minHeight: 100,
    backgroundColor: theme.colors.surface,
    marginBottom: theme.spacing.xl,
  },

  locationHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.sm,
  },
  locationControls: { flexDirection: 'row', alignItems: 'center' },
  savedAddressSection: {
    marginBottom: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  savedAddressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  savedAddressTitle: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    fontWeight: '700',
  },
  savedAddressManage: {
    ...theme.typography.caption,
    color: theme.colors.primary,
    fontWeight: '700',
  },
  savedAddressList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  savedAddressChip: {
    minWidth: 150,
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surface,
  },
  savedAddressChipSelected: { backgroundColor: theme.colors.primary },
  savedAddressChipText: { flexShrink: 1 },
  savedAddressChipLabel: {
    ...theme.typography.caption,
    color: theme.colors.textPrimary,
    fontWeight: '700',
  },
  savedAddressChipLabelSelected: { color: theme.colors.surface },
  savedAddressChipDetail: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    fontSize: 10,
  },
  savedAddressChipDetailSelected: { color: theme.colors.surface },
  addSavedAddressButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    alignSelf: 'flex-start',
    marginBottom: theme.spacing.md,
  },
  currentLocationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.infoBackground,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: theme.spacing.sm,
  },
  addressSearchStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    marginTop: -theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  addressSearchStatusText: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
  },
  addressResults: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.md,
    marginTop: -theme.spacing.md,
    marginBottom: theme.spacing.md,
    overflow: 'hidden',
  },
  addressResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.borderLight,
  },
  addressResultText: {
    ...theme.typography.body2,
    color: theme.colors.textPrimary,
    flex: 1,
  },
  attribution: {
    ...theme.typography.caption,
    color: theme.colors.textTertiary,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
    fontSize: 9,
  },
  addressSearchError: {
    ...theme.typography.caption,
    color: theme.colors.error,
    marginTop: -theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  locationWarning: {
    ...theme.typography.caption,
    color: theme.colors.warning,
    backgroundColor: theme.colors.warningBackground,
    padding: theme.spacing.sm,
    borderRadius: theme.radius.sm,
    marginTop: -theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  manualAddressCard: {
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surface,
    gap: theme.spacing.xs,
  },
  manualAddressTitle: {
    ...theme.typography.label,
    color: theme.colors.textPrimary,
  },
  manualAddressHelp: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    marginBottom: theme.spacing.sm,
  },

  mapGridPattern: {
    position: 'absolute',
    width: '150%',
    height: '150%',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    opacity: 0.5,
    borderRadius: 20,
  },
  mapPin: { zIndex: 2 },
  mapOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 40,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  addressInput: {
    backgroundColor: theme.colors.surface,
    marginBottom: theme.spacing.xl,
  },

  infoCard: {
    backgroundColor: theme.colors.infoBackground,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  infoBullet: {
    color: theme.colors.textSecondary,
    marginBottom: 4,
    lineHeight: 18,
  },
  consentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: theme.spacing.md,
  },
  consentBox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderRadius: 4,
  },
  consentBoxChecked: { backgroundColor: theme.colors.primary },
  manualButton: { alignItems: 'center', paddingVertical: theme.spacing.md },
  submissionError: {
    ...theme.typography.caption,
    color: theme.colors.error,
    textAlign: 'center',
  },
  submissionErrorCard: {
    alignItems: 'center',
    gap: theme.spacing.xs,
    padding: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.errorBackground,
  },
  submissionErrorAction: {
    ...theme.typography.label,
    color: theme.colors.primary,
  },
  profileErrorBanner: {
    backgroundColor: theme.colors.errorBackground,
    borderRadius: theme.radius.md,
    padding: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },

  footer: {
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.layout.screenPadding,
  },
  verificationBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    backgroundColor: theme.colors.warningBackground,
    borderWidth: 1,
    borderColor: theme.colors.warning,
    borderRadius: theme.radius.md,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  subdivisionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.infoBackground,
    borderRadius: theme.radius.md,
    padding: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
});
