import { theme } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  topNav: {
    backgroundColor: '#1e3a8a',
    paddingHorizontal: theme.layout.screenPadding,
    paddingBottom: theme.spacing.md,
  },
  greetingRow: { marginBottom: theme.spacing.md },
  subdivisionRow: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
  subdivisionText: {
    ...theme.typography.caption,
    color: 'rgba(255,255,255,0.8)',
    marginLeft: 4,
  },
  headerTopRow: { flexDirection: 'row', alignItems: 'center' },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.md,
    height: 44,
    marginRight: theme.spacing.sm,
  },
  searchInput: { flex: 1, fontSize: 14, color: theme.colors.textPrimary },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.sm,
  },
  badge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.error,
    borderWidth: 1,
    borderColor: '#1e3a8a',
  },
  avatarButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: theme.colors.surface,
  },
  headerAvatar: { width: '100%', height: '100%' },
  content: { flex: 1, zIndex: 5 },
  contentContainer: {
    paddingBottom: theme.spacing.xxxl,
    paddingTop: theme.spacing.lg,
  },
  mainCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    marginHorizontal: theme.layout.screenPadding,
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    ...theme.shadows.md,
    marginBottom: theme.spacing.xl,
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  categoryItem: {
    width: '25%',
    alignItems: 'center',
    marginBottom: theme.spacing.lg,
  },
  categoryIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme.spacing.xs,
  },
  categoryName: {
    textAlign: 'center',
    color: theme.colors.textPrimary,
    fontSize: 11,
    fontWeight: '500',
  },
  noServicesState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: theme.spacing.xl,
  },
  noServicesText: {
    ...theme.typography.body2,
    color: theme.colors.textSecondary,
    marginTop: theme.spacing.sm,
  },
  seeMoreButton: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  seeMoreText: {
    ...theme.typography.button,
    color: theme.colors.primary,
    fontSize: 13,
  },
  widgetsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: theme.colors.borderLight,
    paddingTop: theme.spacing.md,
  },
  widgetCard: {
    flex: 0.48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
    padding: theme.spacing.md,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },

  aiPromoCard: {
    marginHorizontal: theme.layout.screenPadding,
    backgroundColor: '#1e40af',
    borderRadius: theme.radius.xl,
    flexDirection: 'row',
    overflow: 'hidden',
    marginBottom: theme.spacing.xl,
    ...theme.shadows.md,
  },
  aiPromoContent: {
    flex: 1.5,
    padding: theme.spacing.lg,
    justifyContent: 'center',
  },
  aiPromoButton: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: theme.radius.full,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  aiPromoImage: { flex: 1, opacity: 0.9 },

  section: { marginBottom: theme.spacing.xl },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: theme.layout.screenPadding,
    marginBottom: theme.spacing.md,
  },
  promoScroll: { paddingHorizontal: theme.layout.screenPadding, flexGrow: 0 },
  promoCard: {
    width: 280,
    height: 160,
    borderRadius: theme.radius.xl,
    marginRight: theme.spacing.md,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  promoTitle: { color: theme.colors.surface, marginBottom: 4 },
  promoSubtitle: { color: theme.colors.surface, opacity: 0.9 },
  bannerContainer: {
    marginHorizontal: theme.layout.screenPadding,
    backgroundColor: '#f3e8ff',
    borderRadius: theme.radius.xl,
    flexDirection: 'row',
    overflow: 'hidden',
    marginBottom: theme.spacing.xl,
    height: 120,
  },
  bannerContent: {
    flex: 1,
    padding: theme.spacing.lg,
    justifyContent: 'center',
  },
  bannerButton: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 8,
    borderRadius: theme.radius.full,
    alignSelf: 'flex-start',
    marginTop: theme.spacing.sm,
  },
  bannerImage: { width: 140, height: '100%' },
  recommendedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: theme.layout.screenPadding,
  },
  recommendedCard: {
    width: '48%',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    overflow: 'hidden',
    marginBottom: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  recommendedImageContainer: { height: 140, width: '100%' },
  promoTag: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: '#f97316',
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 4,
  },
  providerBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: theme.colors.warning,
    padding: 2,
    borderRadius: 4,
  },
  providerAvatar: { width: 24, height: 24, borderRadius: 2 },
  recommendedInfo: { padding: theme.spacing.sm },
  recommendedMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: theme.spacing.xs,
  },
  ratingRow: { flexDirection: 'row', alignItems: 'center' },
  distanceRow: { flexDirection: 'row', alignItems: 'center' },
});
