import { theme } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.spacing.md,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  content: { flex: 1, paddingVertical: theme.spacing.lg },
  workerInfo: { alignItems: 'center', marginBottom: theme.spacing.xxxl },
  avatarPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: theme.colors.border,
    marginBottom: theme.spacing.md,
  },
  sectionTitle: { marginBottom: theme.spacing.sm },
  starsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: theme.spacing.xxxl,
  },
  starBtn: { padding: theme.spacing.xs, marginHorizontal: theme.spacing.xs },
  textArea: {
    minHeight: 100,
    backgroundColor: theme.colors.surface,
    marginBottom: theme.spacing.xl,
  },
  photoScroll: {
    flexDirection: 'row',
    marginBottom: theme.spacing.xl,
    flexGrow: 0,
  },
  uploadBtn: {
    width: 80,
    height: 80,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.infoBackground,
    marginRight: theme.spacing.md,
  },
  photoPreview: {
    width: 80,
    height: 80,
    borderRadius: theme.radius.md,
    marginRight: theme.spacing.md,
    position: 'relative',
  },
  reviewImage: {
    flex: 1,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.border,
  },
  removePhotoBtn: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  recommendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    marginBottom: theme.spacing.xxxl,
    ...theme.shadows.sm,
  },
  footer: { paddingVertical: theme.spacing.md },
});
