packages:
  - apps/*
  - packages/*
  - tests/*

overrides:
  expo-router>@expo/metro-runtime: '6.1.2'
  '@types/react-dom': '19.1.11'
  postcss: '8.5.19'
  uuid: '11.1.1'

allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  puppeteer: true
  sharp: true
  supabase: true
  unrs-resolver: true
